name: Build changed images
on:
  push:
    paths:
      - "*.def"
# Not very robust
jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
     - id: files
       uses: jitterbit/get-changed-files@v1
     - name: build
       uses: ./.github/workflows/build_containers.yml
       with:
        image-name: ${{ files.all }}

